//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class terraNostraEntities1 : DbContext
    {
        public terraNostraEntities1()
            : base("name=terraNostraEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<areaComun> areaComun { get; set; }
        public virtual DbSet<incidente> incidente { get; set; }
        public virtual DbSet<informacion> informacion { get; set; }
        public virtual DbSet<plan_cobro> plan_cobro { get; set; }
        public virtual DbSet<plan_residencia> plan_residencia { get; set; }
        public virtual DbSet<reservacion> reservacion { get; set; }
        public virtual DbSet<residencia> residencia { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<rubro_cobro> rubro_cobro { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
