//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(PlanCobroMetaData))]
    public partial class plan_cobro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plan_cobro()
        {
            this.plan_residencia = new HashSet<plan_residencia>();
        }
    
        public int id { get; set; }
        public string detail { get; set; }
        public int residenciaId { get; set; }
        public int rubroCobroId { get; set; }
        public System.DateTime datePlan { get; set; }
        public int estado { get; set; }
        public decimal total { get; set; }
        public string value;
        public string estadoDetail
        {
            get
            {
                if (estado ==1)
                {
                    return value;
                }
                else
                {
                    //DEFAULT value here. 
                    return null;
                }
            }
            set
            {
                if (estado==1)
                {
                    value = "Pagado";
                }
                else
                {
                    //DEFAULT Value. 
                    value = "Pendiente";
                }
            }
        }
        


        public virtual rubro_cobro rubro_cobro { get; set; }
        public virtual residencia residencia_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plan_residencia> plan_residencia { get; set; }
    }
}
