//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
  
namespace Infraestructure.Models
{  
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class reservacion
    {
        public int id { get; set; }
        public int areaComunId { get; set; }
        public int usuario { get; set; }
        public string detalle { get; set; }
        public int estado { get; set; }
        public Nullable<System.DateTime> dateFrom { get; set; }
        public Nullable<System.DateTime> dateTo { get; set; }
    
        public virtual areaComun areaComun { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
